apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deploymentName }}
spec:
  selector:
    app: {{ .Values.deploymentName }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
